# Stage 1: Build the Express API
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build:api

# Stage 2: Run the Express app
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist/apps/api ./
COPY --from=build /app/package*.json ./
RUN npm install --omit=dev
EXPOSE 3333
CMD ["node", "main.js"]
