# Stage 1: Build the Angular app
FROM node:18 AS build
WORKDIR /app
COPY package*.json ./
RUN npm install  --force
COPY . .
RUN nx run ui:build-storybook

# Stage 2: Serve the Angular app with Nginx
FROM nginx:alpine
COPY --from=build /app/dist/apps/dist/storybook /usr/share/nginx/html
EXPOSE 81
CMD ["nginx", "-g", "daemon off;"]
